### ISSUE TITLE
oobabooga on another server - how to setup?

### ISSUE THREAD

**Issue by LightTemplar** [if-ai/IF_prompt_MKR#3]
How to setup, if I have oobabooga installed on another machine?

**Comment by if-ai** [comment]
I will add a way to dynamically set it on the settings but for now the only way is by manually change the ip on the scrips/if_prompt_mkr.py
![msedge_R225pCQNjW](https://github.com/if-ai/IF_prompt_MKR/assets/21185218/8e0b3b20-53a0-413d-adc4-7789ff3686ca)

**Comment by if-ai** [comment]
I added the feature to use another ip check the video later is uploading now

**Comment by LightTemplar** [comment]
From the logs looks like connection is working! Though, I still didn't get that beautiful result from your images :)

**Comment by if-ai** [comment]
what is the prompt you get? did you get the prompt, could you take a screenshot of the image + prompt?

**Comment by LightTemplar** [comment]
Thanks to your video, I got it working =)
I only had to use TheBloke/WizardLM-7B-V1-0-Uncensored-SuperHOT-8K-GGML with Transformers because I ain't got enough vram for 13B GPTQ model with Exllama. 
My result for the promt "(CatGirl warrior:1.2), legendary flower" was: 
![00127-2811832964](https://github.com/if-ai/IF_prompt_MKR/assets/453783/bdccaa02-6608-434c-a9c9-11c80bc453fc)

**Comment by if-ai** [comment]
That's fantastic thank you so much for showing your result.

Did it work with server or only local.

I will make my own checks this weekend but it would be nice to know, so far
I could only run local, so is hard for me to tell if something doesn't work
if people don't tell me.

**Comment by LightTemplar** [comment]
I understand! They are two VMs on two PCs in local network. 
For oobabooga I got 5GB VRAM (Quadro P2200), and for AUTO1111 - 12 GB VRAM (RTX 3060)
