### ISSUE TITLE
GGUF version

### ISSUE THREAD

**Issue by vivi-gomez** [if-ai/IF_prompt_MKR#8]
Are you planning to release a GGUF model?

**Comment by if-ai** [comment]
![Ga06czy1RP](https://github.com/if-ai/IF_prompt_MKR/assets/21185218/84e9f81a-19c3-4636-8fe8-91ac6451cc95)
Yes, I am doing as we speak, hopefully I can release the 7B gguf version this week.  The problem I was having is that I have been using my personal computer for work and the instances for lambda labs were always taken every time I had a chance in the pic bellow
![msedge_LJ60GU5evO](https://github.com/if-ai/IF_prompt_MKR/assets/21185218/1cb97638-d76b-4a51-8c56-6efdd86a7319)

I am saving for another 3090 to do the bigger models on my own PC so those are coming too I also plan to do some base on PHi or tiny llama later

**Comment by if-ai** [comment]
[impactframes/IFpromptMKR-7b-L2-gguf-q4_k_m](https://huggingface.co/impactframes/IFpromptMKR-7b-L2-gguf-q4_k_m)
